# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yoshinari Fujinuma's Page
tagline:          'A Jekyll theme'
description:      'Welcome and have some coffee here!'
url:              
baseurl:          /

author:
  name:           'Yoshinari Fujinuma'
  url:            https://twitter.com/akkikiki

paginate:         5

# Custom vars
version:          2.1.0

twitter_username: akkikiki
github_username:  akkikiki

github:
  repo:           https://github.com/akkikiki
